name: Documentation

on:
  push:
    branches:
      - "main"
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/docs
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      
      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docs/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    name: Deploy Docker containers
    runs-on: self-hosted
    needs: build
    # if: github.ref == "ref/heads/main"
    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/id_rsa

      - name: SSH Deploy
        run: |
          ssh -i ~/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOSTNAME }} << "EOF"
            docker pull ${{ env.REGISTRY }}/rwth-time/scystream-sdk/docs:latest
            docker compose down && docker compose up -d
          EOF
